import type { DocumentTemplate } from "../types";

/**
 * Benin Document Templates
 *
 * Document templates adapted for Beninese construction practices.
 * Documents are primarily in French, reflecting the official
 * language of Benin and the language of legal and administrative
 * proceedings.
 */
export const BENIN_TEMPLATES: DocumentTemplate[] = [
  {
    id: "benin-contrat-construction",
    name: "Contrat de construction",
    type: "CONTRACT",
    phase: "ASSEMBLE",
    description:
      "Construction agreement between the maitre d'ouvrage (owner/client) and the chef de chantier or entreprise de construction. Defines scope of work, payment schedule, timeline, responsibilities for material procurement, and conditions for termination. This document protects both parties and should be signed before any work begins.",
    fields: [
      "Maitre d'ouvrage (owner) full name and address",
      "Entrepreneur/chef de chantier full name and address",
      "Project description and location (parcelle reference, commune)",
      "Scope of work (detailed description of all phases included)",
      "Reference to architectural plans (plan number and date)",
      "Total contract amount in CFA",
      "Payment schedule tied to milestones",
      "Material procurement responsibility (owner or contractor)",
      "Start date and estimated completion date",
      "Penalty clause for delays (if applicable)",
      "Conditions for contract modification (avenant)",
      "Dispute resolution mechanism",
      "Signatures of both parties and witnesses",
    ],
    required: true,
  },
  {
    id: "benin-devis-estimatif",
    name: "Devis estimatif",
    type: "BID",
    phase: "ASSEMBLE",
    description:
      "Detailed cost estimate (devis) prepared by the chef de chantier, entreprise, or architect. Breaks down the project cost by phase and line item, including quantities, unit prices, and totals for materials and labor. The devis is the primary budgeting reference document throughout the build.",
    fields: [
      "Project name and location (commune)",
      "Client (maitre d'ouvrage) name",
      "Prepared by (name and contact)",
      "Date of preparation",
      "Line items grouped by construction phase",
      "For each item: description, unit, quantity, unit price (CFA), total",
      "Subtotal for materials per phase",
      "Subtotal for labor (main d'oeuvre) per phase",
      "Phase totals",
      "Grand total (montant total HT)",
      "Contingency amount (imprevus, typically 10-15%)",
      "Total TTC (all taxes included, if applicable)",
      "Validity period of the devis",
    ],
    required: true,
  },
  {
    id: "benin-bon-commande-materiaux",
    name: "Bon de commande materiaux",
    type: "OTHER",
    phase: "BUILD",
    description:
      "Material purchase order used to track all material purchases during construction. Essential for budget control and preventing material theft — a common problem on unattended construction sites. Each material delivery should have a corresponding bon de commande signed by the owner or their representative.",
    fields: [
      "Order number and date",
      "Supplier name and contact",
      "Delivery site address (commune, quartier)",
      "List of materials ordered (item, quantity, unit price)",
      "Total amount in CFA",
      "Payment method (cash, MTN Mobile Money, bank transfer)",
      "Expected delivery date",
      "Received by (name and signature)",
      "Quantity actually delivered (to compare with order)",
      "Notes on quality or discrepancies",
    ],
    required: false,
  },
  {
    id: "benin-bordereau-prix",
    name: "Bordereau de prix",
    type: "BID",
    phase: "ASSEMBLE",
    description:
      "Price schedule listing unit prices for all work items. Unlike the devis estimatif which gives totals, the bordereau provides the per-unit rates used to calculate payment for actual quantities of work performed. Useful when exact quantities may vary during construction.",
    fields: [
      "Project name and reference",
      "Contractor name",
      "Date of preparation",
      "Category of work (grouped by trade/phase)",
      "Item description",
      "Unit of measurement (sqm, linear meter, lump sum, etc.)",
      "Unit price for materials",
      "Unit price for labor",
      "Combined unit price",
      "Notes on price validity and conditions",
      "Signature of contractor",
      "Approval signature of owner",
    ],
    required: false,
  },
  {
    id: "benin-pv-reception-provisoire",
    name: "Proces-verbal de reception provisoire",
    type: "REPORT",
    phase: "VERIFY",
    description:
      "Provisional acceptance report documenting the formal handover of the completed building from the contractor to the owner. Lists any reserves (deficiencies) that must be corrected. The reception provisoire starts the warranty period — typically 1 year for visible defects and 10 years for structural defects (garantie decennale) when an architect is involved.",
    fields: [
      "Date and location of reception",
      "Project name and address (commune, quartier)",
      "Maitre d'ouvrage (owner) name",
      "Entrepreneur/contractor name",
      "Architect name (if applicable)",
      "Description of work completed",
      "List of reserves (deficiencies to be corrected)",
      "Deadline for correction of reserves",
      "Amount of retenue de garantie (retention, if applicable)",
      "Declaration of reception (with or without reserves)",
      "Signatures of all parties present",
    ],
    required: true,
  },
  {
    id: "benin-pv-reception-definitive",
    name: "Proces-verbal de reception definitive",
    type: "REPORT",
    phase: "OPERATE",
    description:
      "Definitive acceptance report issued after the warranty period (typically 1 year after reception provisoire) if all reserves have been corrected. This final document releases the contractor from short-term warranty obligations.",
    fields: [
      "Date of reception definitive",
      "Reference to the reception provisoire (date and PV number)",
      "Confirmation that all reserves have been corrected",
      "Statement on any new defects discovered during warranty period",
      "Release of retenue de garantie (if applicable)",
      "Final payment amount (if any balance remaining)",
      "Declaration of definitive reception",
      "Signatures of owner, contractor, and architect (if applicable)",
    ],
    required: false,
  },
  {
    id: "benin-quittance-paiement",
    name: "Quittance de paiement",
    type: "RECEIPT",
    phase: "BUILD",
    description:
      "Payment receipt documenting each payment made to the contractor, workers, or suppliers. Essential for financial tracking, especially for diaspora builders who need to verify that funds sent from abroad are being used correctly. Every payment should generate a signed quittance.",
    fields: [
      "Receipt number and date",
      "Payer (maitre d'ouvrage or representative) name",
      "Recipient name and role (contractor, worker, supplier)",
      "Amount paid in CFA",
      "Payment method (cash, MTN Mobile Money, Wave, bank transfer)",
      "Purpose of payment (phase, milestone, or specific work)",
      "Running total of payments to date (for this recipient)",
      "Remaining balance (if part of a larger agreement)",
      "Signature of recipient",
      "Signature or acknowledgment of payer",
    ],
    required: true,
  },
  {
    id: "benin-plan-de-masse",
    name: "Plan de masse",
    type: "PLAN",
    phase: "DESIGN",
    description:
      "Site plan showing the building footprint positioned on the parcelle, including setbacks from property lines, access routes, perimeter wall, fosse septique location, well or borehole position, and utility connections. Required for the permis de construire application.",
    fields: [
      "Parcelle boundaries with dimensions",
      "Building footprint with setback dimensions",
      "Orientation (north arrow)",
      "Access from the road (vehicular and pedestrian)",
      "Perimeter wall (cloture) layout",
      "Gate (portail) location",
      "Fosse septique position and distance from building",
      "Well or borehole location (if applicable)",
      "Utility connection points (SBEE, SONEB)",
      "Neighboring buildings (existing)",
      "Scale and title block",
    ],
    required: true,
  },
  {
    id: "benin-demande-permis-construire",
    name: "Demande de permis de construire",
    type: "PERMIT",
    phase: "APPROVE",
    description:
      "Building permit application form submitted to the mairie. This is the official request to begin construction and must be accompanied by the required supporting documents.",
    fields: [
      "Applicant (maitre d'ouvrage) full name and address",
      "Parcelle location (commune, arrondissement, quartier/village, lot number)",
      "Type of construction (residential, commercial, mixed)",
      "Number of floors (R+0, R+1, R+2, etc.)",
      "Total built area in square meters",
      "Estimated construction cost in CFA",
      "Reference to CPF number or ANDF registration receipt",
      "Architect name and registration number (if applicable)",
      "List of attached documents",
      "Date and signature of applicant",
    ],
    required: true,
  },
  {
    id: "benin-attestation-conformite",
    name: "Attestation de conformite",
    type: "REPORT",
    phase: "VERIFY",
    description:
      "Certificate of conformity issued by the architect confirming that the completed building matches the approved plans and meets acceptable quality standards. May also be requested by the Direction departementale du Cadre de Vie for larger projects.",
    fields: [
      "Architect name and registration number",
      "Project name and address (commune, quartier)",
      "Reference to approved plans (plan number and date)",
      "Reference to permis de construire (number and date)",
      "Statement of conformity to approved plans",
      "Any deviations from the original plans (noted and justified)",
      "Statement on structural quality",
      "Date of inspection",
      "Architect's stamp and signature",
    ],
    required: false,
  },
];
