import type { InspectionRequirement } from "../types";

export const USA_INSPECTIONS: InspectionRequirement[] = [
  {
    id: "usa-insp-footing",
    name: "Footing Inspection",
    phase: "BUILD",
    milestone: "Foundation",
    description:
      "Verifies that footing trenches are dug to the correct depth and width, rebar is placed per the structural plan, and soil bearing conditions are adequate before concrete is poured.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Footing dimensions match approved plans (depth, width)",
      "Rebar size, spacing, and lap splices per structural drawings",
      "Trench bottom is undisturbed native soil or compacted fill",
      "No standing water or loose soil in trench",
      "Step footings properly formed on sloped sites",
      "Footing drain tile installed where required",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-foundation",
    name: "Foundation/Slab Pre-Pour Inspection",
    phase: "BUILD",
    milestone: "Foundation",
    description:
      "Inspects foundation forms, rebar, anchor bolts, and under-slab utilities before concrete is placed. Confirms the foundation will meet structural and dimensional requirements.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Foundation forms are level, plumb, and properly braced",
      "Rebar placement matches structural plans",
      "Anchor bolt locations and embedment depth per plan",
      "Under-slab plumbing and conduit installed and inspected",
      "Vapor barrier installed over prepared sub-grade",
      "Gravel base compacted to specification",
      "Form dimensions match approved foundation plan",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-framing",
    name: "Framing Inspection",
    phase: "BUILD",
    milestone: "Framing",
    description:
      "Comprehensive inspection of the structural framing including walls, floors, roof, and connections. Verifies that the building skeleton matches the approved plans and meets code requirements.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Wall stud size, spacing, and height per plans",
      "Headers and beams sized correctly for span",
      "Roof trusses or rafters installed per engineered drawings",
      "Sheathing nailing pattern meets code requirements",
      "Floor joist size, spacing, and bearing conditions",
      "Fireblocking installed at all required locations",
      "Proper nailing and connector hardware at all connections",
      "Window and door rough openings match schedule",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-shearwall",
    name: "Shear Wall/Hold-Down Inspection",
    phase: "BUILD",
    milestone: "Framing",
    description:
      "Verifies that lateral force-resisting elements (shear walls, hold-downs, and tie-downs) are installed per the structural engineer's design. Critical for wind and seismic resistance.",
    inspector: "Licensed engineer",
    checklistItems: [
      "Shear wall sheathing nailing pattern per schedule",
      "Hold-down hardware installed at correct locations",
      "Anchor bolts and foundation connections verified",
      "Continuous load path from roof to foundation",
      "Simpson or equivalent connector hardware properly installed",
      "Blocking and backing at shear panel edges",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-rough-plumbing",
    name: "Rough Plumbing Inspection",
    phase: "BUILD",
    milestone: "Rough-ins",
    description:
      "Inspects all water supply and drain/waste/vent (DWV) piping installed within walls, floors, and ceilings before they are covered. Includes pressure testing of supply lines.",
    inspector: "City/county building inspector",
    checklistItems: [
      "All supply piping properly supported and secured",
      "DWV pipe sizes match code requirements",
      "Proper venting for all fixtures per plumbing code",
      "Supply lines pass pressure test (no leaks)",
      "DWV system passes air or water test",
      "Cleanout access points at required locations",
      "Pipe penetrations through fire-rated assemblies firestopped",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-rough-electrical",
    name: "Rough Electrical Inspection",
    phase: "BUILD",
    milestone: "Rough-ins",
    description:
      "Inspects all electrical wiring, boxes, and panel connections installed within walls, ceilings, and floors before drywall covers them. Verifies NEC code compliance.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Wire sizes match circuit breaker amperage ratings",
      "Proper box fill calculations (not overfilled)",
      "GFCI protection in kitchens, baths, garages, and exterior",
      "AFCI protection in bedrooms and required living areas",
      "Smoke and CO detector wiring at all required locations",
      "Grounding and bonding per NEC requirements",
      "Cable stapling and support within required distances",
      "Panel schedule matches approved electrical plan",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-rough-hvac",
    name: "Rough HVAC Inspection",
    phase: "BUILD",
    milestone: "Rough-ins",
    description:
      "Inspects ductwork, refrigerant lines, gas piping, and equipment rough-in before walls and ceilings are closed. Verifies proper sizing based on Manual J calculations.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Ductwork properly sized per Manual D calculations",
      "All duct connections sealed with mastic or approved tape",
      "Refrigerant lines properly insulated and supported",
      "Gas piping tested and leak-free",
      "Combustion air provisions for gas appliances",
      "Return air pathways adequate for each zone",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-insulation-energy",
    name: "Insulation/Energy Inspection",
    phase: "BUILD",
    milestone: "Insulation",
    description:
      "Verifies that insulation R-values meet energy code requirements for the climate zone, air sealing is complete, and vapor barriers are correctly installed before drywall.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Wall insulation R-value meets energy code for climate zone",
      "Ceiling/attic insulation R-value meets requirements",
      "Floor/crawl space insulation properly installed",
      "Air sealing complete at all penetrations and gaps",
      "Vapor barrier on correct side per climate zone",
      "No gaps, voids, or compression in insulation",
      "Rim joist and band board insulated and air sealed",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-pre-drywall",
    name: "Pre-Drywall Inspection",
    phase: "BUILD",
    milestone: "Insulation",
    description:
      "Final check of all work inside wall and ceiling cavities before drywall covers everything. This is the last opportunity to verify framing corrections, blocking, fire stopping, and rough-in quality.",
    inspector: "City/county building inspector",
    checklistItems: [
      "All rough-in inspections have been passed",
      "Fire blocking installed at all required locations",
      "Backing and blocking for future fixtures and accessories",
      "All framing corrections from prior inspections completed",
      "Low-voltage wiring (data, cable, security) installed",
      "Bathtub and shower pan installed and tested",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-final-plumbing",
    name: "Final Plumbing Inspection",
    phase: "VERIFY",
    milestone: "Final inspections",
    description:
      "Inspects all installed plumbing fixtures, verifies proper operation of supply and drainage, and confirms hot water delivery and water heater installation meet code.",
    inspector: "City/county building inspector",
    checklistItems: [
      "All fixtures connected and operational",
      "No visible leaks at any connection or fixture",
      "Hot water delivered to all required fixtures",
      "Water heater installation meets code (strapping, venting, T&P relief)",
      "Exterior hose bibs have anti-siphon protection",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-final-electrical",
    name: "Final Electrical Inspection",
    phase: "VERIFY",
    milestone: "Final inspections",
    description:
      "Verifies all electrical devices, fixtures, and panels are installed, labeled, and operational. Confirms GFCI/AFCI devices function properly and smoke/CO detectors are working.",
    inspector: "City/county building inspector",
    checklistItems: [
      "All outlets, switches, and fixtures installed and operational",
      "Panel directory completed and accurate",
      "GFCI outlets test and reset properly",
      "AFCI breakers test properly",
      "Smoke detectors and CO alarms operational",
      "Exterior lighting and outlet covers installed",
      "Appliance connections complete and safe",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-final-building",
    name: "Final Building Inspection",
    phase: "VERIFY",
    milestone: "Final inspections",
    description:
      "Comprehensive final inspection covering structural, life safety, accessibility, and general code compliance. Must pass before a Certificate of Occupancy can be issued.",
    inspector: "City/county building inspector",
    checklistItems: [
      "Egress windows and doors meet size and operation requirements",
      "Stairways, railings, and guards meet code dimensions",
      "Garage-to-house separation (fire-rated wall and self-closing door)",
      "Address numbers visible from the street",
      "Grading provides positive drainage away from foundation",
      "Driveway and walkways completed",
      "All prior inspection corrections verified as complete",
      "Mechanical equipment accessible for service",
    ],
    requiredBeforeNext: true,
    formal: true,
  },
  {
    id: "usa-insp-certificate-occupancy",
    name: "Certificate of Occupancy",
    phase: "VERIFY",
    milestone: "Occupancy",
    description:
      "The final official document issued by the local building authority confirming the structure is safe for habitation and complies with all applicable building codes. Required before anyone can legally move in.",
    inspector: "City/county building inspector",
    checklistItems: [
      "All final trade inspections passed (plumbing, electrical, mechanical)",
      "Final building inspection passed",
      "Fire department approval obtained (if required)",
      "Health department approval for septic (if applicable)",
      "All permit conditions satisfied",
      "As-built survey filed (if required by jurisdiction)",
    ],
    requiredBeforeNext: false,
    formal: true,
  },
];
