import type { DocumentTemplate } from "../types";

export const USA_TEMPLATES: DocumentTemplate[] = [
  {
    id: "usa-bid-request",
    name: "Bid Request Form",
    type: "BID",
    phase: "ASSEMBLE",
    description:
      "A standardized form sent to contractors requesting a detailed bid for your project. Includes project description, scope of work, timeline requirements, and instructions for bid submission to ensure you receive comparable proposals.",
    fields: [
      "Project name",
      "Project address",
      "Owner name and contact information",
      "Project description and scope of work",
      "Plans and specifications reference",
      "Bid due date",
      "Estimated start date",
      "Estimated completion date",
      "Insurance requirements",
      "Bid format instructions",
      "Required inclusions and exclusions",
      "Site visit date and instructions",
      "Questions deadline and contact",
      "Evaluation criteria",
    ],
    required: true,
  },
  {
    id: "usa-gc-agreement",
    name: "General Contractor Agreement",
    type: "CONTRACT",
    phase: "ASSEMBLE",
    description:
      "The primary contract between the owner and the general contractor. Defines scope, price, payment schedule, timeline, change order procedures, warranty terms, insurance requirements, and dispute resolution for the entire construction project.",
    fields: [
      "Owner name and address",
      "Contractor name, address, and license number",
      "Project address and legal description",
      "Scope of work with detailed specifications",
      "Contract price (fixed or cost-plus terms)",
      "Payment schedule tied to milestones",
      "Start date and substantial completion date",
      "Liquidated damages for late completion",
      "Change order procedures and approval requirements",
      "Insurance requirements (general liability, workers compensation)",
      "Warranty terms (workmanship, materials, structural)",
      "Dispute resolution method (mediation, arbitration, litigation)",
      "Termination conditions and procedures",
      "Lien waiver requirements",
      "Allowance items and adjustment procedures",
      "Permits responsibility",
      "Cleanup and site maintenance requirements",
    ],
    required: true,
  },
  {
    id: "usa-subcontractor-agreement",
    name: "Subcontractor Agreement",
    type: "CONTRACT",
    phase: "ASSEMBLE",
    description:
      "A contract between the general contractor (or owner-builder) and a subcontractor for a specific trade or portion of the work. Defines the sub's scope, price, schedule, insurance, and payment terms.",
    fields: [
      "General contractor or owner name",
      "Subcontractor name, address, and license number",
      "Project address",
      "Scope of work for the specific trade",
      "Contract price",
      "Payment terms and schedule",
      "Start date and completion date",
      "Insurance requirements",
      "Warranty terms",
      "Materials responsibility (who furnishes what)",
      "Cleanup requirements",
      "Change order procedures",
      "Lien waiver requirements",
      "Safety requirements and OSHA compliance",
    ],
    required: false,
  },
  {
    id: "usa-change-order",
    name: "Change Order Form",
    type: "CONTRACT",
    phase: "BUILD",
    description:
      "Documents any modification to the original contract scope, including the description of the change, the cost impact (addition or credit), the timeline impact, and required approvals before work proceeds.",
    fields: [
      "Change order number",
      "Project name and address",
      "Date of request",
      "Requested by (owner, contractor, or architect)",
      "Description of change",
      "Reason for change",
      "Cost impact (itemized labor and materials)",
      "Timeline impact (days added or saved)",
      "Revised contract total",
      "Revised completion date",
      "Owner approval signature and date",
      "Contractor approval signature and date",
      "Architect approval signature and date (if applicable)",
    ],
    required: true,
  },
  {
    id: "usa-draw-request",
    name: "Draw Request",
    type: "INVOICE",
    phase: "BUILD",
    description:
      "A formal request to the construction lender for disbursement of funds tied to a completed construction milestone. Includes percentage of completion, work verified, and amount requested.",
    fields: [
      "Draw request number",
      "Project name and address",
      "Loan number",
      "Borrower name",
      "Contractor name",
      "Draw period dates",
      "Milestone or phase completed",
      "Percentage of overall completion",
      "Amount previously disbursed",
      "Amount requested this draw",
      "Remaining loan balance after draw",
      "Itemized cost breakdown by category",
      "Lien waivers attached (yes/no)",
      "Inspection date and inspector name",
      "Supporting photographs attached (yes/no)",
      "Contractor certification signature",
      "Owner certification signature",
    ],
    required: true,
  },
  {
    id: "usa-lien-waiver-partial",
    name: "Lien Waiver (Partial / Progress)",
    type: "LEGAL",
    phase: "BUILD",
    description:
      "A document signed by the contractor, subcontractor, or supplier acknowledging receipt of a progress payment and waiving lien rights for the amount received to date. Collected with each progress payment to protect the owner.",
    fields: [
      "Project name and address",
      "Claimant name (contractor, sub, or supplier)",
      "Claimant address and license number",
      "Owner name",
      "Payment amount received",
      "Payment period or through-date",
      "Total amount paid to date",
      "Remaining contract balance",
      "Conditional or unconditional designation",
      "Claimant signature and date",
      "Notarization (if required by state)",
    ],
    required: true,
  },
  {
    id: "usa-lien-waiver-final",
    name: "Lien Waiver (Final)",
    type: "LEGAL",
    phase: "VERIFY",
    description:
      "A document signed upon final payment that waives all lien rights against the property. Collected from the general contractor, every subcontractor, and every major supplier before the owner makes the final payment.",
    fields: [
      "Project name and address",
      "Claimant name (contractor, sub, or supplier)",
      "Claimant address and license number",
      "Owner name",
      "Final payment amount",
      "Total contract amount paid",
      "Statement that all labor and materials have been paid",
      "Unconditional waiver of all lien rights",
      "Claimant signature and date",
      "Notarization (if required by state)",
    ],
    required: true,
  },
  {
    id: "usa-insurance-request",
    name: "Certificate of Insurance Request",
    type: "OTHER",
    phase: "ASSEMBLE",
    description:
      "A letter requesting that a contractor or subcontractor provide a certificate of insurance showing current general liability and workers compensation coverage, with the owner listed as an additional insured party.",
    fields: [
      "Owner name and address",
      "Contractor or subcontractor name",
      "Project name and address",
      "Required coverage types (general liability, workers compensation, auto)",
      "Minimum coverage amounts",
      "Additional insured requirement",
      "Certificate holder information",
      "Response deadline",
      "Insurance company contact for verification",
    ],
    required: true,
  },
  {
    id: "usa-inspection-request",
    name: "Inspection Request Form",
    type: "CHECKLIST",
    phase: "BUILD",
    description:
      "A form used to request a building department inspection at each required checkpoint during construction. Documents the inspection type, requested date, and preparation checklist to ensure the inspection passes on the first visit.",
    fields: [
      "Permit number",
      "Project address",
      "Owner name",
      "Contractor name and contact",
      "Inspection type (foundation, framing, plumbing rough, electrical rough, mechanical rough, insulation, final)",
      "Requested inspection date",
      "Site access instructions",
      "Preparation checklist for the specific inspection type",
      "Previous inspection results (if re-inspection)",
      "Corrections completed since last inspection",
      "Contact person on site",
    ],
    required: true,
  },
  {
    id: "usa-punch-list",
    name: "Punch List Template",
    type: "CHECKLIST",
    phase: "VERIFY",
    description:
      "A detailed room-by-room checklist for documenting all incomplete, defective, or substandard items that must be corrected before final payment. Each item includes location, description, responsible party, and completion status.",
    fields: [
      "Project name and address",
      "Date of walkthrough",
      "Participants (owner, contractor, architect)",
      "Item number",
      "Room or location",
      "Trade or category",
      "Description of deficiency",
      "Priority (safety, functional, cosmetic)",
      "Responsible party",
      "Photo reference number",
      "Target completion date",
      "Date completed",
      "Verified by and verification date",
    ],
    required: true,
  },
  {
    id: "usa-material-approval",
    name: "Material Approval Form",
    type: "OTHER",
    phase: "BUILD",
    description:
      "A form for documenting owner approval of specific materials, finishes, or products before they are ordered or installed. Prevents disputes over material selections and ensures the installed product matches expectations.",
    fields: [
      "Project name and address",
      "Date of submission",
      "Submitted by",
      "Material or product description",
      "Manufacturer and model number",
      "Color, finish, or pattern",
      "Location where material will be installed",
      "Sample or cut sheet attached (yes/no)",
      "Cost (if different from allowance amount)",
      "Lead time for delivery",
      "Owner approval signature and date",
      "Contractor acknowledgment signature and date",
    ],
    required: false,
  },
  {
    id: "usa-payment-schedule",
    name: "Payment Schedule",
    type: "INVOICE",
    phase: "ASSEMBLE",
    description:
      "A detailed schedule linking each payment to a specific construction milestone, including the percentage of the contract, the dollar amount, the triggering milestone, and the verification required before payment is released.",
    fields: [
      "Project name and address",
      "Owner name",
      "Contractor name",
      "Total contract amount",
      "Payment number",
      "Milestone or phase description",
      "Percentage of contract",
      "Dollar amount",
      "Verification required (inspection, photos, lien waiver)",
      "Estimated date of milestone",
      "Actual date completed",
      "Date payment issued",
      "Cumulative amount paid",
      "Remaining balance",
      "Retainage percentage and amount",
    ],
    required: true,
  },
  {
    id: "usa-warranty-log",
    name: "Warranty Tracking Log",
    type: "CHECKLIST",
    phase: "OPERATE",
    description:
      "A comprehensive log of all warranties for your new home, including builder workmanship, mechanical systems, structural elements, appliances, roofing, and other components. Tracks coverage periods, claim procedures, and expiration dates.",
    fields: [
      "Project name and address",
      "Item or system covered",
      "Warranty provider (builder, manufacturer, installer)",
      "Provider contact information",
      "Warranty type (workmanship, materials, structural, product)",
      "Coverage start date",
      "Coverage end date",
      "Coverage description and limitations",
      "Claim procedure",
      "Actions that void the warranty",
      "Claim history (date, issue, resolution)",
      "Documentation location (receipt, certificate, manual)",
    ],
    required: false,
  },
  {
    id: "usa-move-in-checklist",
    name: "Move-In Checklist",
    type: "CHECKLIST",
    phase: "OPERATE",
    description:
      "A structured checklist for the first week in your new home covering utility setup, safety system testing, appliance registration, key systems orientation, and administrative tasks that are easy to overlook during the excitement of moving in.",
    fields: [
      "Utility account setup (electric, gas, water, sewer, trash, internet)",
      "Meter readings recorded",
      "All locks re-keyed or codes changed",
      "Smoke detectors tested",
      "Carbon monoxide detectors tested",
      "Fire extinguisher locations identified",
      "Main water shut-off located and labeled",
      "Electrical panel located and circuits labeled",
      "Gas shut-off located and labeled",
      "HVAC filter size recorded and spare purchased",
      "Thermostat programmed",
      "Appliance warranties registered",
      "Homeowners insurance policy confirmed active",
      "Property tax payment schedule confirmed",
      "HOA contact information and rules obtained",
      "Emergency contacts posted (police, fire, poison control, utilities)",
    ],
    required: false,
  },
  {
    id: "usa-closeout-report",
    name: "Project Close-Out Report",
    type: "REPORT",
    phase: "VERIFY",
    description:
      "A comprehensive summary document created at project completion that records the final budget versus original budget, timeline versus original schedule, all change orders, key lessons learned, and a complete record of the project for future reference.",
    fields: [
      "Project name and address",
      "Owner name",
      "Contractor name",
      "Project start date and completion date",
      "Original budget and final cost",
      "Budget variance by category",
      "Original schedule and actual schedule",
      "Schedule variance by phase",
      "Total number of change orders and net cost impact",
      "Summary of major changes and reasons",
      "Final inspection date and CO number",
      "Key lessons learned",
      "Contractor performance summary",
      "Subcontractor contact list for future reference",
      "Outstanding warranty items",
      "Document archive location",
    ],
    required: false,
  },
];
