import type { DocumentTemplate, DocumentType } from "@keystone/market-data";
import type { ProjectData, ContactData, BudgetItemData } from "./project-service";

export interface DocumentContext {
  project: ProjectData;
  contacts?: ContactData[];
  budgetItems?: BudgetItemData[];
  customFields?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Shared HTML / CSS infrastructure
// ---------------------------------------------------------------------------

const PRINT_STYLES = `
  @media print {
    body { margin: 0; padding: 0; }
    .no-print { display: none !important; }
  }
  @page {
    size: letter;
    margin: 1in;
  }
`;

const BASE_STYLES = `
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: Georgia, 'Times New Roman', serif;
    font-size: 11pt;
    line-height: 1.55;
    color: #1a1a1a;
    max-width: 8.5in;
    margin: 0 auto;
    padding: 1in;
    background: #fff;
  }
  h1, h2, h3, h4 {
    font-family: Arial, Helvetica, sans-serif;
    color: #2C1810;
    margin-bottom: 0.4em;
  }
  h1 { font-size: 18pt; border-bottom: 2px solid #D4A574; padding-bottom: 6px; margin-bottom: 16px; }
  h2 { font-size: 13pt; margin-top: 20px; }
  h3 { font-size: 11pt; margin-top: 14px; }
  p { margin-bottom: 8px; }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
  }
  th, td {
    border: 1px solid #D4A574;
    padding: 6px 10px;
    text-align: left;
    font-size: 10pt;
  }
  th {
    background: #F5E6D3;
    font-family: Arial, Helvetica, sans-serif;
    font-weight: 600;
    color: #2C1810;
    font-size: 9pt;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }
  .blank {
    display: inline-block;
    min-width: 200px;
    border-bottom: 1px solid #333;
    padding: 0 4px;
    margin: 0 2px;
  }
  .blank-short {
    display: inline-block;
    min-width: 100px;
    border-bottom: 1px solid #333;
    padding: 0 4px;
    margin: 0 2px;
  }
  .signature-block {
    display: flex;
    gap: 40px;
    margin-top: 40px;
    page-break-inside: avoid;
  }
  .signature-line {
    flex: 1;
    padding-top: 60px;
    border-top: 1px solid #333;
    font-size: 9pt;
    font-family: Arial, Helvetica, sans-serif;
  }
  .header-meta {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: 20px;
  }
  .header-meta .brand {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 8pt;
    color: #6A6A6A;
    text-transform: uppercase;
    letter-spacing: 2px;
  }
  .header-meta .date {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    color: #3A3A3A;
  }
  .disclaimer {
    margin-top: 30px;
    padding: 10px 14px;
    border: 1px solid #D4A574;
    background: #FDF8F0;
    font-size: 8pt;
    color: #6A6A6A;
    font-style: italic;
    page-break-inside: avoid;
  }
  .section { margin-bottom: 16px; }
  .field-row { margin-bottom: 8px; }
  .field-label {
    font-family: Arial, Helvetica, sans-serif;
    font-size: 9pt;
    font-weight: 600;
    color: #2C1810;
    display: inline;
  }
  .field-value { display: inline; }
  .checkbox-item {
    display: flex;
    align-items: flex-start;
    gap: 8px;
    margin-bottom: 6px;
    page-break-inside: avoid;
  }
  .checkbox {
    width: 14px;
    height: 14px;
    border: 1.5px solid #2C1810;
    border-radius: 2px;
    flex-shrink: 0;
    margin-top: 2px;
  }
  .checkbox-text { font-size: 10pt; }
  .page-break { page-break-before: always; }
  .total-row { font-weight: bold; background: #F5E6D3; }
  .amount { font-family: 'Courier New', monospace; text-align: right; }
  .fr-label { color: #6A6A6A; font-style: italic; font-size: 9pt; }
  hr { border: none; border-top: 1px solid #D4A574; margin: 16px 0; }
`;

function wrapHtml(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)}</title>
<style>${BASE_STYLES}${PRINT_STYLES}</style>
</head>
<body>
${bodyHtml}
</body>
</html>`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function headerBlock(title: string, date: string): string {
  return `<div class="header-meta">
  <div class="brand">Keystone</div>
  <div class="date">${escapeHtml(date)}</div>
</div>
<h1>${escapeHtml(title)}</h1>`;
}

function disclaimerBlock(): string {
  return `<div class="disclaimer">
  Generated by Keystone. This document is a template and should be reviewed by a qualified professional before use.
</div>`;
}

function signatureLines(...labels: string[]): string {
  const lines = labels
    .map(
      (l) =>
        `<div class="signature-line">${escapeHtml(l)}<br><span style="font-size:8pt;color:#6A6A6A;">Date: <span class="blank-short">&nbsp;</span></span></div>`
    )
    .join("\n    ");
  return `<div class="signature-block">\n    ${lines}\n</div>`;
}

function fieldLine(label: string, value: string | undefined, frLabel?: string): string {
  const display = value && value.trim() ? escapeHtml(value) : '<span class="blank">&nbsp;</span>';
  const fr = frLabel ? ` <span class="fr-label">(${escapeHtml(frLabel)})</span>` : "";
  return `<div class="field-row"><span class="field-label">${escapeHtml(label)}${fr}:</span> <span class="field-value">${display}</span></div>`;
}

function formatCurrency(amount: number, currency: string): string {
  if (currency === "XOF" || currency === "CFA") {
    return new Intl.NumberFormat("fr-FR", { style: "decimal", maximumFractionDigits: 0 }).format(amount) + " FCFA";
  }
  if (currency === "GHS") {
    return "GH\u20B5" + new Intl.NumberFormat("en-GH", { style: "decimal", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
  }
  return "$" + new Intl.NumberFormat("en-US", { style: "decimal", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(amount);
}

function today(): string {
  return new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function isTogo(ctx: DocumentContext): boolean {
  return ctx.project.market === "TOGO" || ctx.project.market === "BENIN";
}

function getCurrency(ctx: DocumentContext): string {
  return ctx.project.currency ?? (isTogo(ctx) ? "XOF" : "USD");
}

function makeCf(ctx: DocumentContext): (label: string) => string {
  return (label: string) => ctx.customFields?.[label] ?? "";
}

// ---------------------------------------------------------------------------
// CONTRACT generator
// ---------------------------------------------------------------------------

function generateContract(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const currency = getCurrency(ctx);
  const togo = isTogo(ctx);
  const contractor = ctx.contacts?.find((c) =>
    c.role.toLowerCase().includes("contractor") ||
    c.role.toLowerCase().includes("chef") ||
    c.role.toLowerCase().includes("entreprise")
  );

  let body = headerBlock(template.name, today());

  if (togo) {
    body += `<p class="fr-label">Contrat entre le maitre d'ouvrage et l'entrepreneur</p>`;
  }

  body += `<div class="section">
<h2>1. Parties${togo ? ' <span class="fr-label">(Les parties)</span>' : ""}</h2>
${fieldLine("Owner / Client", cf("Owner name and address") || cf("Maitre d'ouvrage (owner) full name and address") || ctx.project.name, togo ? "Maitre d'ouvrage" : undefined)}
${fieldLine("Contractor", contractor?.name ?? cf("Contractor name, address, and license number") ?? cf("Entrepreneur/chef de chantier full name and address"), togo ? "Entrepreneur" : undefined)}
${contractor?.phone ? fieldLine("Contractor Phone", contractor.phone) : ""}
${contractor?.email ? fieldLine("Contractor Email", contractor.email) : ""}
</div>`;

  body += `<div class="section">
<h2>2. Project Description${togo ? ' <span class="fr-label">(Description du projet)</span>' : ""}</h2>
${fieldLine("Project Name", ctx.project.name)}
${fieldLine("Property Type", ctx.project.propertyType)}
${fieldLine("Size", ctx.project.sizeRange ?? ctx.project.details)}
${fieldLine("Market", ctx.project.market)}
</div>`;

  body += `<div class="section">
<h2>3. Scope of Work${togo ? ' <span class="fr-label">(Etendue des travaux)</span>' : ""}</h2>
<p>${escapeHtml(cf("Scope of work with detailed specifications") || cf("Scope of work (detailed description of all phases included)") || "The Contractor shall furnish all labor, materials, equipment, and services necessary for the complete construction as described in the project plans and specifications.")}</p>
</div>`;

  body += `<div class="section">
<h2>4. Contract Price${togo ? ' <span class="fr-label">(Montant du contrat)</span>' : ""}</h2>
${fieldLine("Total Contract Amount", ctx.project.totalBudget ? formatCurrency(ctx.project.totalBudget, currency) : undefined)}
${fieldLine("Payment Terms", cf("Payment schedule tied to milestones") || cf("Contract price (fixed or cost-plus terms)") || "Per attached payment schedule")}
</div>`;

  // Payment schedule table if budget items available
  if (ctx.budgetItems && ctx.budgetItems.length > 0) {
    body += `<div class="section">
<h2>5. Payment Schedule${togo ? ' <span class="fr-label">(Echeancier de paiement)</span>' : ""}</h2>
<table>
<tr><th>#</th><th>Category${togo ? " / Phase" : ""}</th><th>Estimated Amount</th><th>Status</th></tr>`;
    ctx.budgetItems.forEach((item, i) => {
      body += `<tr>
  <td>${i + 1}</td>
  <td>${escapeHtml(item.category)}</td>
  <td class="amount">${formatCurrency(item.estimated, currency)}</td>
  <td>${escapeHtml(item.status)}</td>
</tr>`;
    });
    body += `<tr class="total-row">
  <td colspan="2">Total</td>
  <td class="amount">${formatCurrency(ctx.budgetItems.reduce((s, b) => s + b.estimated, 0), currency)}</td>
  <td></td>
</tr>`;
    body += `</table></div>`;
  }

  body += `<div class="section">
<h2>${ctx.budgetItems ? "6" : "5"}. Timeline${togo ? ' <span class="fr-label">(Delais)</span>' : ""}</h2>
${fieldLine("Start Date", cf("Start date") || cf("Start date and substantial completion date"), togo ? "Date de debut" : undefined)}
${fieldLine("Estimated Completion", cf("Estimated completion date") || cf("Estimated completion date"), togo ? "Date d'achevement prevue" : undefined)}
${fieldLine("Total Duration", ctx.project.totalWeeks ? `${ctx.project.totalWeeks} weeks` : undefined)}
</div>`;

  body += `<div class="section">
<h2>${ctx.budgetItems ? "7" : "6"}. General Conditions${togo ? ' <span class="fr-label">(Conditions generales)</span>' : ""}</h2>
<p><strong>Change Orders:</strong> Any changes to the scope of work must be documented in writing and signed by both parties before work proceeds.</p>
<p><strong>Insurance:</strong> The Contractor shall maintain adequate general liability and workers compensation insurance throughout the project.</p>
<p><strong>Warranty:</strong> The Contractor warrants all workmanship for a period of ${togo ? "one (1) year from reception provisoire, with garantie decennale for structural defects" : "one (1) year from the date of substantial completion"}.</p>
<p><strong>Dispute Resolution:</strong> ${cf("Dispute resolution method (mediation, arbitration, litigation)") || cf("Dispute resolution mechanism") || "Any disputes arising under this agreement shall be resolved first through good-faith negotiation, then through mediation."}</p>
<p><strong>Termination:</strong> Either party may terminate this agreement with thirty (30) days written notice and payment for all work completed to date.</p>
</div>`;

  body += signatureLines(
    togo ? "Maitre d'ouvrage (Owner)" : "Owner",
    togo ? "Entrepreneur (Contractor)" : "Contractor",
    "Witness"
  );

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// BID REQUEST generator
// ---------------------------------------------------------------------------

function generateBidRequest(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const currency = getCurrency(ctx);
  const togo = isTogo(ctx);

  let body = headerBlock(template.name, today());

  if (togo) {
    body += `<p class="fr-label">Demande de devis / Appel d'offres</p>`;
  }

  body += `<div class="section">
<h2>Project Information${togo ? ' <span class="fr-label">(Informations du projet)</span>' : ""}</h2>
${fieldLine("Project Name", ctx.project.name)}
${fieldLine("Property Type", ctx.project.propertyType)}
${fieldLine("Size", ctx.project.sizeRange ?? ctx.project.details)}
${fieldLine("Location", cf("Project address") || cf("Project name and location"))}
${fieldLine("Owner", cf("Owner name and contact information") || cf("Client (maitre d'ouvrage) name"))}
</div>`;

  body += `<div class="section">
<h2>Scope of Work${togo ? ' <span class="fr-label">(Description des travaux)</span>' : ""}</h2>
<p>${escapeHtml(cf("Project description and scope of work") || "Please provide a detailed bid for the scope of work described below and in the attached plans and specifications.")}</p>
${fieldLine("Plans Reference", cf("Plans and specifications reference") || cf("Reference to architectural plans (plan number and date)"))}
</div>`;

  body += `<div class="section">
<h2>Submission Requirements${togo ? ' <span class="fr-label">(Exigences de soumission)</span>' : ""}</h2>
${fieldLine("Bid Due Date", cf("Bid due date") || cf("Validity period of the devis"), togo ? "Date limite" : undefined)}
${fieldLine("Estimated Start Date", cf("Estimated start date"), togo ? "Date de debut estimee" : undefined)}
${fieldLine("Estimated Completion", cf("Estimated completion date"))}
</div>`;

  body += `<div class="section">
<h2>Bid Format${togo ? ' <span class="fr-label">(Format du devis)</span>' : ""}</h2>
<p>${escapeHtml(cf("Bid format instructions") || "Please itemize your bid by category, including separate line items for labor and materials. Include unit prices where applicable.")}</p>
${fieldLine("Required Inclusions", cf("Required inclusions and exclusions"))}
</div>`;

  if (!togo) {
    body += `<div class="section">
<h2>Insurance and Licensing</h2>
${fieldLine("Insurance Requirements", cf("Insurance requirements"))}
<p>Please include copies of your current general liability insurance certificate and state contractor license with your bid submission.</p>
</div>`;
  }

  body += `<div class="section">
<h2>Evaluation Criteria${togo ? ' <span class="fr-label">(Criteres d\'evaluation)</span>' : ""}</h2>
<p>${escapeHtml(cf("Evaluation criteria") || "Bids will be evaluated on price, experience, references, proposed timeline, and completeness of submission.")}</p>
</div>`;

  body += `<div class="section">
<h2>Contact${togo ? ' <span class="fr-label">(Contact)</span>' : ""}</h2>
${fieldLine("Questions Contact", cf("Questions deadline and contact"))}
${fieldLine("Site Visit", cf("Site visit date and instructions"))}
</div>`;

  if (ctx.project.totalBudget) {
    body += `<div class="section">
<h2>Budget Reference</h2>
<p>Approximate project budget: <strong>${formatCurrency(ctx.project.totalBudget, currency)}</strong></p>
</div>`;
  }

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// CHECKLIST generator
// ---------------------------------------------------------------------------

function generateChecklist(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const togo = isTogo(ctx);

  let body = headerBlock(template.name, today());

  if (togo) {
    body += `<p class="fr-label">Liste de verification</p>`;
  }

  body += `<div class="section">
<h2>Project Details${togo ? ' <span class="fr-label">(Details du projet)</span>' : ""}</h2>
${fieldLine("Project Name", ctx.project.name)}
${fieldLine("Date", cf("Date of walkthrough") || today())}
${fieldLine("Location", cf("Project address") || cf("Project name and address"))}
</div>`;

  body += `<hr>`;
  body += `<div class="section">
<h2>Checklist Items</h2>`;

  template.fields.forEach((field) => {
    body += `<div class="checkbox-item">
  <div class="checkbox"></div>
  <div class="checkbox-text">${escapeHtml(field)}${cf(field) ? `: <em>${escapeHtml(cf(field))}</em>` : ""}</div>
</div>`;
  });

  body += `</div>`;

  body += `<div class="section" style="margin-top:24px;">
<h2>Notes${togo ? ' <span class="fr-label">(Remarques)</span>' : ""}</h2>
<div style="border:1px solid #D4A574;min-height:120px;padding:8px;">
${cf("Notes") ? escapeHtml(cf("Notes")) : "&nbsp;"}
</div>
</div>`;

  body += signatureLines("Inspector / Reviewer", "Owner");

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// INVOICE (Draw Request) generator
// ---------------------------------------------------------------------------

function generateInvoice(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const currency = getCurrency(ctx);
  const togo = isTogo(ctx);

  let body = headerBlock(template.name, today());

  if (togo) {
    body += `<p class="fr-label">Demande de decaissement / Facture</p>`;
  }

  body += `<div class="section">
${fieldLine("Draw / Invoice Number", cf("Draw request number") || cf("Order number and date"))}
${fieldLine("Project Name", ctx.project.name)}
${fieldLine("Date", today())}
</div>`;

  body += `<div class="section">
<h2>Parties${togo ? ' <span class="fr-label">(Les parties)</span>' : ""}</h2>
${fieldLine(togo ? "Owner (Maitre d'ouvrage)" : "Borrower / Owner", cf("Borrower name") || cf("Payer (maitre d'ouvrage or representative) name"))}
${fieldLine("Contractor", cf("Contractor name") || ctx.contacts?.find((c) => c.role.toLowerCase().includes("contractor"))?.name)}
${!togo ? fieldLine("Loan Number", cf("Loan number")) : ""}
</div>`;

  body += `<div class="section">
<h2>Cost Breakdown${togo ? ' <span class="fr-label">(Detail des couts)</span>' : ""}</h2>`;

  if (ctx.budgetItems && ctx.budgetItems.length > 0) {
    body += `<table>
<tr><th>Category</th><th>Estimated</th><th>Spent to Date</th><th>This Draw</th><th>Remaining</th></tr>`;
    let totalEstimated = 0;
    let totalSpent = 0;
    ctx.budgetItems.forEach((item) => {
      totalEstimated += item.estimated;
      totalSpent += item.actual;
      const remaining = item.estimated - item.actual;
      body += `<tr>
  <td>${escapeHtml(item.category)}</td>
  <td class="amount">${formatCurrency(item.estimated, currency)}</td>
  <td class="amount">${formatCurrency(item.actual, currency)}</td>
  <td class="amount"><span class="blank-short">&nbsp;</span></td>
  <td class="amount">${formatCurrency(remaining > 0 ? remaining : 0, currency)}</td>
</tr>`;
    });
    body += `<tr class="total-row">
  <td>Total</td>
  <td class="amount">${formatCurrency(totalEstimated, currency)}</td>
  <td class="amount">${formatCurrency(totalSpent, currency)}</td>
  <td class="amount"><span class="blank-short">&nbsp;</span></td>
  <td class="amount">${formatCurrency(totalEstimated - totalSpent > 0 ? totalEstimated - totalSpent : 0, currency)}</td>
</tr>`;
    body += `</table>`;
  } else {
    body += `<p>${escapeHtml(cf("Itemized cost breakdown by category") || "See attached itemized breakdown.")}</p>`;
  }

  body += `</div>`;

  body += `<div class="section">
<h2>Summary${togo ? ' <span class="fr-label">(Resume)</span>' : ""}</h2>
${fieldLine("Total Budget", ctx.project.totalBudget ? formatCurrency(ctx.project.totalBudget, currency) : undefined)}
${fieldLine("Previously Disbursed", ctx.project.totalSpent ? formatCurrency(ctx.project.totalSpent, currency) : cf("Amount previously disbursed"))}
${fieldLine("Amount Requested", cf("Amount requested this draw") || cf("Amount paid in CFA"))}
${fieldLine("Completion Percentage", ctx.project.progress ? `${ctx.project.progress}%` : cf("Percentage of overall completion"))}
</div>`;

  body += signatureLines(
    togo ? "Maitre d'ouvrage (Owner)" : "Owner / Borrower",
    togo ? "Entrepreneur (Contractor)" : "Contractor"
  );

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// RECEIPT generator
// ---------------------------------------------------------------------------

function generateReceipt(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const currency = getCurrency(ctx);
  const togo = isTogo(ctx);

  let body = headerBlock(template.name, today());

  if (togo) {
    body += `<p class="fr-label">Quittance de paiement / Recu</p>`;
  }

  body += `<div class="section" style="text-align:center;margin-bottom:24px;">
<h2 style="border:2px solid #2C1810;display:inline-block;padding:6px 24px;">PAYMENT RECEIPT${togo ? ' / QUITTANCE' : ""}</h2>
</div>`;

  body += `<div class="section">
${fieldLine("Receipt Number", cf("Receipt number and date") || cf("Receipt number"))}
${fieldLine("Date", today())}
</div>`;

  body += `<div class="section">
<h2>Payment Details${togo ? ' <span class="fr-label">(Details du paiement)</span>' : ""}</h2>
<table>
<tr><th>Field</th><th>Details</th></tr>
<tr><td>Payer${togo ? " (Payeur)" : ""}</td><td>${escapeHtml(cf("Payer (maitre d'ouvrage or representative) name") || cf("Payer") || ctx.project.name)}</td></tr>
<tr><td>Recipient${togo ? " (Beneficiaire)" : ""}</td><td>${escapeHtml(cf("Recipient name and role (contractor, worker, supplier)") || cf("Recipient") || "")}<span class="blank">&nbsp;</span></td></tr>
<tr><td>Amount${togo ? " (Montant)" : ""}</td><td><strong>${escapeHtml(cf("Amount paid in CFA") || cf("Amount") || "")}</strong><span class="blank">&nbsp;</span></td></tr>
<tr><td>Payment Method${togo ? " (Mode de paiement)" : ""}</td><td>${escapeHtml(cf("Payment method (cash, Wave, mobile money, bank transfer)") || cf("Payment method") || "")}<span class="blank">&nbsp;</span></td></tr>
<tr><td>Purpose${togo ? " (Objet)" : ""}</td><td>${escapeHtml(cf("Purpose of payment (phase, milestone, or specific work)") || cf("Purpose") || "")}<span class="blank">&nbsp;</span></td></tr>
<tr><td>Running Total${togo ? " (Cumul)" : ""}</td><td>${escapeHtml(cf("Running total of payments to date (for this recipient)") || cf("Running total") || "")}<span class="blank">&nbsp;</span></td></tr>
<tr><td>Remaining Balance${togo ? " (Solde restant)" : ""}</td><td>${escapeHtml(cf("Remaining balance (if part of a larger agreement)") || cf("Remaining balance") || "")}<span class="blank">&nbsp;</span></td></tr>
</table>
</div>`;

  body += `<div class="section">
<h2>Project Reference</h2>
${fieldLine("Project", ctx.project.name)}
${fieldLine("Total Budget", ctx.project.totalBudget ? formatCurrency(ctx.project.totalBudget, currency) : undefined)}
${fieldLine("Total Spent to Date", ctx.project.totalSpent ? formatCurrency(ctx.project.totalSpent, currency) : undefined)}
</div>`;

  body += signatureLines(
    togo ? "Beneficiaire (Recipient)" : "Recipient",
    togo ? "Payeur (Payer)" : "Payer"
  );

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// GENERIC fallback generator (LEGAL, PERMIT, PLAN, REPORT, OTHER)
// ---------------------------------------------------------------------------

function generateGeneric(template: DocumentTemplate, ctx: DocumentContext): string {
  const cf = makeCf(ctx);
  const togo = isTogo(ctx);

  let body = headerBlock(template.name, today());

  body += `<div class="section">
<p><em>${escapeHtml(template.description)}</em></p>
</div>`;

  body += `<div class="section">
<h2>Project Information${togo ? ' <span class="fr-label">(Informations du projet)</span>' : ""}</h2>
${fieldLine("Project Name", ctx.project.name)}
${fieldLine("Property Type", ctx.project.propertyType)}
${fieldLine("Market", ctx.project.market)}
${fieldLine("Size", ctx.project.sizeRange ?? ctx.project.details)}
${fieldLine("Current Phase", ctx.project.phaseName)}
</div>`;

  body += `<hr>`;
  body += `<div class="section">
<h2>Document Fields</h2>`;

  template.fields.forEach((field) => {
    body += fieldLine(field, cf(field));
  });

  body += `</div>`;

  body += signatureLines("Signature", "Date");

  body += disclaimerBlock();

  return wrapHtml(template.name, body);
}

// ---------------------------------------------------------------------------
// Main dispatcher
// ---------------------------------------------------------------------------

const GENERATORS: Record<string, (t: DocumentTemplate, c: DocumentContext) => string> = {
  CONTRACT: generateContract,
  BID: generateBidRequest,
  CHECKLIST: generateChecklist,
  INVOICE: generateInvoice,
  RECEIPT: generateReceipt,
};

export function generateDocument(
  template: DocumentTemplate,
  context: DocumentContext
): string {
  const generator = GENERATORS[template.type] ?? generateGeneric;
  return generator(template, context);
}

export { generateContract, generateBidRequest, generateChecklist, generateInvoice, generateReceipt };
