"use client";

import { useEffect, useState } from "react";
import { useTopbar } from "../layout";
import { LEARN_MODULES } from "@/lib/data/mock-projects";
import { Badge } from "@/components/ui/Badge";
import { ChevronDown, ChevronRight } from "lucide-react";

const LESSON_CONTENT: Record<string, string[]> = {
  "Construction loan types explained": [
    "Construction loans are specialized short-term financing products designed to fund the building of a new home. The most common type is the construction-to-permanent loan (also called a single-close loan), which converts automatically into a traditional mortgage once building is complete. This saves you from paying two sets of closing costs and simplifies the process considerably. During the construction phase, you typically make interest-only payments on the amount disbursed so far, rather than the full loan amount.",
    "A stand-alone construction loan is a separate short-term loan that covers only the building period, usually 12 to 18 months. Once construction is complete, you must refinance into a permanent mortgage through a second closing. While this means two sets of closing costs and two approval processes, it can offer more flexibility if you want to shop for the best permanent mortgage rate after building. Stand-alone loans often have variable interest rates that are higher than conventional mortgages.",
    "Government-backed options include FHA construction loans (FHA 203k for renovation or FHA One-Time Close for new builds) and VA construction loans for eligible veterans. FHA loans allow down payments as low as 3.5% but require mortgage insurance. VA construction loans offer zero down payment but require VA-approved builders. Hard money loans are another option, typically from private lenders, offering fast approval with less documentation but at significantly higher interest rates (often 10-15%) and shorter terms. These are more common for experienced investors or fix-and-flip projects.",
    "Your DTI, or debt-to-income ratio, is a critical factor in qualifying for any construction loan. DTI is calculated by dividing your total monthly debt payments (including the projected new mortgage payment) by your gross monthly income. Most conventional lenders require a DTI below 43%, though some allow up to 50%. FHA loans may accept DTIs up to 50% with strong compensating factors. To improve your chances of qualification, pay down existing debts, avoid taking on new credit, and ensure your income documentation is thorough and accurate.",
  ],
  "How to read a floor plan": [
    "A floor plan is a scaled, two-dimensional drawing showing a building as if viewed from directly above with the roof removed. The most important element to understand first is scale. Most residential floor plans use a scale of 1/4 inch equals 1 foot, meaning every quarter inch on the paper represents one real foot. Dimensions are typically marked with lines and arrows between walls, showing room sizes in feet and inches (in the US) or meters (in West Africa and most other countries). Always check the scale indicator on the drawing before measuring anything.",
    "Walls appear as parallel lines on a floor plan. Thick double lines represent exterior walls (which are wider because they contain insulation and sheathing), while thinner double lines indicate interior partition walls. Doors are shown as a line with an arc indicating the direction the door swings open. A pocket door appears as a line sliding into the wall. Windows are shown as thin parallel lines within a wall, sometimes with a thicker line indicating the glass pane. Sliding windows or doors show two overlapping rectangles.",
    "Room labels are placed in the center of each space, identifying its function (bedroom, kitchen, bathroom, closet, etc.) and often including the room dimensions. Electrical symbols are standardized: small circles on walls represent light switches, circles with lines radiating outward indicate ceiling light fixtures, small parallel lines on walls mark electrical outlets, and triangles typically denote special outlets like 220V for dryers or ranges. Plumbing fixtures (toilets, sinks, tubs, showers) are drawn in simplified outline form showing their approximate footprint.",
    "When reviewing a floor plan, pay attention to traffic flow -- how you move from room to room. Look for hallways that waste space, doors that collide when opened simultaneously, and whether the kitchen has a practical work triangle between the sink, stove, and refrigerator. Check that bedrooms have adequate closet space and that bathrooms are not visible from public areas when doors are open. Understanding floor plans before construction begins saves significant money, because changes on paper cost nothing compared to changes during building.",
  ],
  "The 12 trades: who does what and when": [
    "Residential construction involves a sequence of specialized trades, each responsible for a specific building system. The work flows in a logical order because each trade builds upon the previous one. Excavation comes first: this crew clears the site, grades the land, digs the foundation trenches or basement, and ensures proper drainage. Next is concrete work, including pouring the foundation footings, foundation walls, and slab. In West African construction, the concrete crew also builds the structural columns (poteaux) and beams (poutres) that form the building skeleton. The framing crew then builds the structural skeleton of the house using wood (in the US) or fills in concrete block walls between the columns (in West Africa).",
    "Once the structure is enclosed, the roofing crew installs roof sheathing, underlayment, and the final roofing material (shingles, metal panels, or tiles). With the building now weather-tight, the mechanical trades begin their rough-in work. Plumbers run supply lines (copper or PEX tubing) and drain/vent pipes (PVC) through walls and floors. Electricians pull wire through the framing, install outlet and switch boxes, and connect the main electrical panel. HVAC technicians install ductwork, set furnaces or air handlers, and place the condensing unit outside. These three mechanical trades must coordinate carefully because they share the same wall and ceiling cavities.",
    "After rough-in passes inspection, the insulation crew fills exterior wall cavities and the attic with fiberglass batts, spray foam, or blown cellulose to meet energy code requirements. Drywall installers then hang gypsum board sheets over the insulation, tape the seams, and apply multiple coats of joint compound to create smooth wall surfaces. Painters follow with primer and finish coats on all walls, ceilings, and trim. The flooring crew installs tile, hardwood, laminate, or vinyl throughout the house, working room by room.",
    "The final trade is trim and finish carpentry: installing baseboards, crown molding, door casings, interior doors, cabinets, countertops, shelving, and hardware. After trim, the plumber and electrician return for their trim-out phase, installing fixtures like faucets, toilets, light fixtures, switches, and outlet covers. Understanding this sequence matters because scheduling trades out of order creates costly delays. If drywall goes up before rough-in inspection passes, you may have to tear it down. If flooring goes in before painting, paint drips damage the new floors.",
  ],
  "Understanding DTI and loan qualification": [
    "Debt-to-income ratio (DTI) is the single most important number lenders use to determine whether you can afford a mortgage or construction loan. It is calculated by dividing your total monthly debt obligations by your gross (pre-tax) monthly income, then expressing the result as a percentage. For example, if you earn $6,000 per month gross and your total monthly debts (car payment, student loans, credit card minimums, and projected new mortgage payment) total $2,400, your DTI is 40%. Lenders use two versions: front-end DTI (housing costs only divided by income) and back-end DTI (all debts divided by income). Back-end DTI is the more critical number.",
    "Most conventional loan programs set a maximum back-end DTI of 43%, though some lenders allow up to 45% with strong credit scores (740+) and significant cash reserves. FHA loans are more lenient, accepting DTIs up to 50% if the borrower has compensating factors such as a large down payment, substantial savings, or minimal payment shock (the difference between current rent and the new mortgage payment). VA loans have no official DTI cap but most VA lenders use 41% as a guideline. For construction loans specifically, lenders may be stricter because of the added risk of building.",
    "The debts included in your DTI calculation are all minimum monthly payments reported on your credit report: auto loans, student loans, personal loans, credit card minimum payments, child support, alimony, and any existing mortgage or rent (which will be replaced by the new projected payment). Monthly expenses like utilities, groceries, insurance premiums, and subscriptions are not included. The projected housing payment includes principal, interest, property taxes, homeowner insurance, and any HOA dues or mortgage insurance (collectively called PITIA).",
    "To improve your DTI before applying for a construction loan, focus on reducing monthly debt payments rather than just overall balances. Paying off a $200/month car loan reduces DTI far more than paying down a credit card with a $25 minimum. Avoid opening new credit accounts, consolidating loans into longer terms (which lowers monthly payments), and consider delaying the loan application until a major debt is paid off. Increasing your documented income through raises, side income reported on tax returns, or adding a co-borrower also directly improves DTI. A difference of just 2-3 percentage points can mean the difference between approval and denial.",
  ],
  "West African land tenure systems": [
    "Land ownership in West Africa operates under a dual system that combines customary (traditional) land rights with formal legal title. Under customary tenure, land is typically held communally by families, clans, or chieftaincies. The family head or chief acts as a custodian rather than an owner in the Western sense, and land is allocated to family members or sold to outsiders through informal agreements. These transactions may involve customary ceremonies, witness signatures, and payments to the family, but they do not automatically confer legal ownership recognized by the state. In many rural and peri-urban areas, customary tenure remains the dominant system.",
    "Formal land title, known in Francophone West Africa as the titre foncier, is the only form of land ownership that provides full legal protection and is recognized by courts and financial institutions. Without a titre foncier, you cannot use land as collateral for a bank loan, and your claim is vulnerable to disputes from family members who may assert competing customary rights. The process of obtaining formal title involves surveying the land, publishing the claim for a public contestation period, paying government fees, and registering the title with the national land registry. In Togo, this process can take 6 to 18 months and costs roughly 5-10% of the land value in fees.",
    "The risk of purchasing land through informal channels is substantial. Double-selling (where the same parcel is sold to multiple buyers by different family members) is common. Boundary disputes arise when parcels are not formally surveyed. Inheritance claims can surface years after a purchase when a distant relative asserts customary rights. In Togo, the 2018 land code reforms attempted to strengthen the formal system, but enforcement remains inconsistent, especially outside Lome. Diaspora buyers are particularly vulnerable because they cannot easily visit the site, verify boundaries in person, or monitor whether someone else is building on their land.",
    "For anyone purchasing land in West Africa, the safest approach is to insist on beginning the titre foncier process before or immediately after the purchase, even if the seller offers only a customary sale agreement. Engage a licensed surveyor (geometre) to establish boundaries, verify that the seller has legitimate authority to sell (not just one family member acting alone), consult a local attorney to review all documents, and obtain witness statements from neighboring landowners confirming the boundaries. The upfront cost of doing this properly is a fraction of the potential loss from a land dispute that could cost you the entire investment.",
  ],
  "Concrete block vs. wood frame construction": [
    "The two dominant residential construction methods in Keystone's target markets are wood-frame construction (standard in the United States) and reinforced concrete block construction (standard in West Africa). Wood framing uses dimensional lumber (2x4 or 2x6 studs) assembled into wall panels, floor joists, and roof trusses. The frame is then sheathed with oriented strand board (OSB) or plywood, wrapped with a moisture barrier, and finished with exterior siding and interior drywall. This method is fast, relatively inexpensive in lumber-rich regions, and allows easy routing of electrical wires and plumbing through wall cavities.",
    "West African construction predominantly uses the poteau-poutre (post-and-beam) method: reinforced concrete columns and beams form the structural skeleton, and the spaces between are filled with concrete masonry units (CMU or parpaings). Walls are then plastered with cement render on both sides. Roofs are typically steel or aluminum sheet on wood or steel purlins. This method is preferred in tropical climates because concrete block resists termites, humidity, and heavy rain far better than wood. It also provides superior thermal mass, absorbing heat during the day and releasing it slowly at night, which moderates indoor temperatures without air conditioning.",
    "Cost comparisons between the two methods depend entirely on the local market. In the US, wood framing is typically 20-30% less expensive than concrete construction for the same floor area, because lumber is abundant, the supply chain is mature, and the labor force is highly trained in wood-frame techniques. In West Africa, concrete block is the more economical choice because cement and sand are locally available, wood of structural quality is expensive and often imported, and the labor force specializes in masonry. Shipping containers of cement arrive regularly at West African ports, making it the default building material.",
    "Each method has distinct trade-offs beyond cost. Wood-frame homes are faster to build (a typical US home can be framed in 1-2 weeks) but are vulnerable to termites, fire, and hurricane winds if not properly engineered. Concrete block construction is slower (walls go up block by block with mortar and reinforcement) but produces a structure with excellent durability against storms, pests, and fire. In hurricane-prone and high-wind regions of both markets, concrete construction with proper reinforcement significantly outperforms wood frame. The choice also affects insurance costs, resale value, and maintenance requirements over the building's lifetime.",
  ],
  "What building inspectors actually check": [
    "Building inspections are mandatory checkpoints in the construction process where a government inspector (or in some markets, an approved third-party inspector) verifies that work meets the applicable building code. In the United States, inspections are legally required and failing one means work must stop until corrections are made. In West African markets, formal inspection systems exist in cities like Lome and Accra but enforcement varies widely. Regardless of local requirements, understanding what inspectors check helps you ensure quality construction even when oversight is limited.",
    "The first major inspection is the foundation inspection, which occurs after footings are dug and reinforcement (rebar) is placed but before concrete is poured. The inspector verifies footing dimensions match the approved plans, rebar is the correct size and spacing, the soil bearing capacity is adequate (no standing water or loose fill), and form boards are properly set. After the foundation is poured and cured, and the structure is framed, the framing inspection checks that wall studs, headers, floor joists, and roof rafters or trusses are the correct size, spacing, and species of lumber specified in the plans. The inspector also verifies that hold-downs, hurricane straps, and other structural connectors are properly installed.",
    "The rough-in inspection (sometimes three separate inspections) is the most detailed. The plumbing rough-in verifies that drain pipes have the correct slope (typically 1/4 inch per foot), supply lines are properly supported, vent pipes extend through the roof, and the system holds pressure when tested. The electrical rough-in checks wire gauge matches circuit amperage, outlets are spaced per code (every 12 feet on walls, dedicated circuits for kitchen and bathrooms), the panel is properly grounded, and all connections are in accessible junction boxes. The HVAC rough-in verifies duct sizing, return air pathways, equipment clearances, and refrigerant line installation.",
    "The insulation inspection confirms that wall cavities and attic spaces meet the required R-values for the climate zone, that vapor barriers are correctly placed, and that no gaps or compression reduce insulation effectiveness. The final inspection is a comprehensive walk-through covering everything: smoke detectors and carbon monoxide alarms in required locations, GFCI outlets in wet areas (kitchens, bathrooms, garages, exteriors), proper stair dimensions and handrail heights, exit door operation, water heater temperature and pressure relief valve discharge, and overall workmanship. Only after passing the final inspection is a certificate of occupancy issued, legally allowing you to move into the home.",
  ],
  "Payment schedules that protect you": [
    "Construction payments work fundamentally differently from buying an existing home. Instead of one lump sum at closing, funds are disbursed in stages called draws (or draw requests) that correspond to completed milestones. A typical draw schedule might include: 10% at land clearing and mobilization, 15% at foundation completion, 20% at framing completion, 15% at rough-in completion, 15% at drywall and insulation, 15% at interior finishes, and 10% at final completion. Each draw should be tied to verified, inspectable work -- never pay ahead of completed milestones.",
    "If you are financing with a construction loan, the lender controls the draw process. When your contractor requests a draw, the lender sends an inspector to verify the work is actually complete before releasing funds. This protects both you and the lender. For self-funded projects (common in West Africa where phased cash construction is the norm), you must act as your own inspector. Before releasing any payment, physically verify (or have a trusted representative verify with timestamped photos) that the claimed work is genuinely complete and matches the agreed specifications. Never accept a contractor's word alone.",
    "Retainage is a critical protection mechanism. This means withholding a percentage of each payment (typically 5-10%) until the entire project is satisfactorily completed. For example, if a $10,000 draw is approved, you release $9,000 and hold back $1,000. The accumulated retainage is only paid after final inspection, punch list completion, and a lien waiver is signed. Retainage motivates contractors to return and finish punch list items (minor defects and incomplete work) rather than moving on to their next job. Without retainage, you lose significant leverage at the end of the project when the contractor's financial incentive to perform quality work is lowest.",
    "To structure payments that protect you: always use a written contract that specifies the exact draw schedule, milestone definitions, and retainage percentage. Require lien waivers with every draw (these documents from the contractor and subcontractors confirm they have been paid and waive the right to place a lien on your property). Never front-load payments -- a contractor asking for 50% upfront is a major warning sign. In West African markets where formal contracts may be less common, still create a written payment schedule signed by both parties with witnesses. Document everything with photos at each payment milestone. These practices dramatically reduce the risk of contractor abandonment or financial disputes.",
  ],
  "Designing for tropical climates": [
    "Building in tropical climates (including coastal West Africa, the Gulf Coast of the United States, and the Caribbean) requires design strategies that address intense heat, high humidity, heavy rainfall, and potential storm exposure. The most fundamental principle is passive ventilation: orienting the building to capture prevailing breezes, incorporating cross-ventilation (openings on opposite walls), and using high ceilings (3 meters or more) to allow hot air to rise away from occupants. In West African construction, louvered windows and ventilation blocks (claustra) are traditional solutions that allow continuous airflow even during rain.",
    "Roof design is critical in tropical climates. Wide overhangs (at least 60-90 cm) protect walls from direct sun and driving rain, significantly extending the life of exterior finishes and reducing cooling loads. Light-colored or reflective roofing materials (white or silver metal sheets, light-colored tiles) reflect solar radiation rather than absorbing it. In the US Gulf Coast, a steep roof pitch (6:12 or greater) helps shed heavy rain and provides better wind resistance. In West Africa, metal roofing on a moderate pitch is standard; ensure sheets are properly overlapped and secured with roofing screws (not nails) to resist wind uplift.",
    "Thermal mass is a major advantage of concrete block construction in tropical climates. Thick masonry walls absorb heat slowly during the day, keeping interiors cooler when it is hottest outside. At night, the walls release stored heat as outdoor temperatures drop. This natural temperature regulation can reduce or eliminate the need for air conditioning. For wood-frame buildings in hot climates, radiant barriers in the attic (reflective foil facing the airspace) and adequate insulation are essential to block heat transfer from the sun-baked roof into living spaces below.",
    "Material selection must account for humidity, insects, and corrosion. Use pressure-treated or naturally rot-resistant lumber for any wood elements (in US construction, ground-contact-rated treated lumber is required within 8 inches of soil). In West Africa, specify hardwood species resistant to termites for roof purlins and door/window frames. All metal components (fasteners, flashing, reinforcement) should be galvanized or stainless steel to resist the corrosive effects of salt air and humidity. For storm resistance, reinforce concrete block walls with vertical rebar filled with grout at regular intervals, strap the roof structure to the walls with hurricane ties, and install impact-rated windows or permanent shutters in storm-prone areas.",
  ],
  "The titre foncier process: 6 steps": [
    "The titre foncier (formal land title certificate) is the definitive proof of land ownership in Togo and other Francophone West African countries. It is the only document that provides full legal protection against competing claims, enables you to use the land as bank collateral, and is recognized in court without question. The process of obtaining a titre foncier involves six main steps and typically takes between 6 and 18 months, depending on the complexity of the case and the efficiency of local administrative offices. While the process requires patience and upfront costs, it is the single most important investment you can make to protect your land purchase.",
    "Step 1: Engage a licensed surveyor (geometre agree) to conduct a formal boundary survey of the parcel. The surveyor plants boundary markers, measures the plot dimensions, records GPS coordinates, and produces an official survey plan (plan topographique). This typically costs between 150,000 and 500,000 FCFA depending on the parcel size and location. Step 2: Assemble your application file, which includes the survey plan, proof of purchase (acte de vente signed by seller and witnesses), identification documents, and a formal written request to the prefect of the jurisdiction where the land is located. Step 3: Submit the application to the Direction de l'Urbanisme et de l'Habitat (or equivalent office) in the relevant prefecture.",
    "Step 4: A public notice (publication) is posted for a period of 30 to 90 days, during which any person with a competing claim to the land may file an opposition. This publication period is a critical safeguard -- it surfaces hidden claims before you have invested heavily in construction. If an opposition is filed, the matter must be resolved (often through mediation or court proceedings) before the process can continue. If no opposition is filed within the publication period, the file advances. Step 5: A government commission visits the site to verify the boundaries, confirm that the parcel matches the survey plan, and interview neighboring landowners to corroborate that no disputes exist.",
    "Step 6: Upon successful completion of all prior steps, the land registry (Conservation Fonciere) issues the titre foncier certificate, which is recorded in the official national land register. Total government fees for the titre foncier process are typically 5-10% of the declared land value, plus the surveyor fees and any legal representation costs. To protect yourself throughout this process, retain a local attorney experienced in land transactions to manage the file, keep certified copies of every document submitted, maintain a timeline log of all interactions with government offices, and never pay fees without obtaining an official receipt. For diaspora buyers managing this process remotely, a power of attorney (procuration) given to a trusted local representative is essential, but ensure it is specific and limited in scope.",
  ],
};

export default function LearnPage() {
  const { setTopbar } = useTopbar();
  const [openModule, setOpenModule] = useState<number | null>(null);

  useEffect(() => {
    setTopbar("Learn", "Knowledge base", "success");
  }, [setTopbar]);

  const handleToggle = (index: number) => {
    setOpenModule(openModule === index ? null : index);
  };

  return (
    <>
      <h1 className="text-[24px] text-earth">Construction Knowledge Base</h1>
      <p className="text-[13px] text-muted mt-1 mb-6">
        Everything you need to know about building, from financing to final inspection.
      </p>

      <div className="space-y-2 animate-stagger">
        {LEARN_MODULES.map((mod, i) => {
          const isOpen = openModule === i;
          return (
            <div
              key={i}
              className="bg-white rounded-xl p-5 card-hover"
            >
              <div
                onClick={() => handleToggle(i)}
                className="flex items-center gap-3 cursor-pointer"
              >
                <div className="w-7 h-7 rounded-full bg-warm flex items-center justify-center shrink-0">
                  <span className="text-clay font-data text-[12px] font-semibold">{i + 1}</span>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-[14px] font-semibold text-earth">{mod.title}</div>
                  <div className="mt-0.5">
                    <Badge variant={mod.variant}>{mod.category}</Badge>
                  </div>
                </div>
                <span className="text-muted shrink-0">
                  {isOpen ? <ChevronDown size={16} /> : <ChevronRight size={16} />}
                </span>
              </div>

              <div
                className={`overflow-hidden transition-all duration-300 ease-in-out ${isOpen ? "animate-expand" : ""}`}
                style={{ maxHeight: isOpen ? "2000px" : "0px" }}
              >
                {LESSON_CONTENT[mod.title] && (
                  <div className="pt-4 mt-4 border-t border-border">
                    {LESSON_CONTENT[mod.title].map((paragraph, j) => (
                      <p key={j} className="text-[12px] text-muted leading-relaxed mb-3">
                        {paragraph}
                      </p>
                    ))}
                    <p className="text-[10px] text-muted italic mt-2">
                      This is educational guidance. Consult a licensed professional for your specific situation.
                    </p>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <div className="mt-6 p-4 rounded-xl bg-warm border border-sand/30 text-[11px] text-muted leading-relaxed text-center">
        All educational content is for general informational purposes only. Always consult licensed
        professionals for advice specific to your project, location, and circumstances.
      </div>
    </>
  );
}
