import type { DocumentTemplate } from "../types";

/**
 * Ghana Document Templates
 *
 * Document templates adapted for Ghanaian construction practices.
 * Documents are in English, reflecting the official language of Ghana.
 */
export const GHANA_TEMPLATES: DocumentTemplate[] = [
  {
    id: "ghana-construction-contract",
    name: "Construction Contract",
    type: "CONTRACT",
    phase: "ASSEMBLE",
    description:
      "Construction agreement between the building owner and the contractor. Defines scope of work, payment schedule, timeline, responsibilities for material procurement, and conditions for termination. This document protects both parties and should be signed before any work begins.",
    fields: [
      "Building owner full name and address",
      "Contractor full name and address",
      "Project description and location (plot reference)",
      "Scope of work (detailed description of all phases included)",
      "Reference to architectural drawings (drawing number and date)",
      "Total contract amount in GHS",
      "Payment schedule tied to milestones",
      "Material procurement responsibility (owner or contractor)",
      "Start date and estimated completion date",
      "Penalty clause for delays (liquidated damages)",
      "Conditions for contract variation",
      "Defects liability period (typically 6-12 months)",
      "Dispute resolution mechanism (arbitration or courts)",
      "Signatures of both parties and witnesses",
    ],
    required: true,
  },
  {
    id: "ghana-bill-of-quantities",
    name: "Bill of Quantities (BOQ)",
    type: "BID",
    phase: "ASSEMBLE",
    description:
      "Detailed bill of quantities prepared by a quantity surveyor, the contractor, or architect. Breaks down the project cost by trade and line item, including quantities, unit prices, and totals for materials and labor. The BOQ is the primary budgeting reference document throughout the build.",
    fields: [
      "Project name and location",
      "Client (building owner) name",
      "Prepared by (name and qualification)",
      "Date of preparation",
      "Line items grouped by trade/work section",
      "For each item: description, unit, quantity, unit rate (GHS), total",
      "Subtotal for materials per section",
      "Subtotal for labor per section",
      "Section totals",
      "Grand total",
      "Contingency amount (typically 10-15%)",
      "Total including contingency",
      "Validity period of the BOQ",
    ],
    required: true,
  },
  {
    id: "ghana-material-purchase-order",
    name: "Material Purchase Order",
    type: "OTHER",
    phase: "BUILD",
    description:
      "Material purchase order used to track all material purchases during construction. Essential for budget control and preventing material theft — a common problem on construction sites in Ghana. Each material delivery should have a corresponding purchase order signed by the owner or their representative.",
    fields: [
      "Order number and date",
      "Supplier name and contact",
      "Delivery site address",
      "List of materials ordered (item, quantity, unit price)",
      "Total amount in GHS",
      "Payment method (cash, mobile money, bank transfer, cheque)",
      "Expected delivery date",
      "Received by (name and signature)",
      "Quantity actually delivered (to compare with order)",
      "Notes on quality or discrepancies",
    ],
    required: false,
  },
  {
    id: "ghana-priced-boq",
    name: "Priced Bill of Quantities",
    type: "BID",
    phase: "ASSEMBLE",
    description:
      "A bill of quantities priced by a contractor as their bid for the work. Used for competitive bidding — send the unpriced BOQ to multiple contractors and compare their priced returns. This is the standard method for contractor selection in Ghana.",
    fields: [
      "Project name and reference",
      "Contractor name and address",
      "Date of pricing",
      "Work section",
      "Item description",
      "Unit of measurement (sqm, linear meter, number, lump sum)",
      "Quantity",
      "Unit rate (GHS)",
      "Amount (GHS)",
      "Section summary totals",
      "Grand total",
      "Contractor's signature and company stamp",
    ],
    required: false,
  },
  {
    id: "ghana-completion-certificate",
    name: "Completion Certificate",
    type: "REPORT",
    phase: "VERIFY",
    description:
      "Certificate documenting the formal handover of the completed building from the contractor to the owner. Lists any outstanding defects (snag list items) that must be corrected during the defects liability period. The completion certificate starts the defects liability period, typically 6-12 months.",
    fields: [
      "Date of completion inspection",
      "Project name and address",
      "Building owner name",
      "Contractor name",
      "Architect name (if applicable)",
      "Description of work completed",
      "List of outstanding defects (snag list)",
      "Deadline for correction of defects",
      "Retention amount withheld (if applicable)",
      "Declaration of practical completion",
      "Defects liability period (start and end dates)",
      "Signatures of all parties present",
    ],
    required: true,
  },
  {
    id: "ghana-defects-certificate",
    name: "Defects Liability Certificate",
    type: "REPORT",
    phase: "OPERATE",
    description:
      "Certificate issued at the end of the defects liability period (typically 6-12 months after completion) confirming that all defects have been corrected. This releases the contractor's retention money and ends their contractual obligation for defect correction.",
    fields: [
      "Date of certificate",
      "Reference to completion certificate (date)",
      "Confirmation that all defects have been corrected",
      "Statement on any new defects discovered during liability period",
      "Release of retention amount",
      "Final account balance (if any remaining)",
      "Declaration of end of defects liability",
      "Signatures of owner, contractor, and architect (if applicable)",
    ],
    required: false,
  },
  {
    id: "ghana-payment-certificate",
    name: "Payment Certificate / Receipt",
    type: "RECEIPT",
    phase: "BUILD",
    description:
      "Payment receipt documenting each payment made to the contractor, workers, or suppliers. Essential for financial tracking, especially for diaspora builders who need to verify that funds sent from abroad are being used correctly. Every payment should generate a signed receipt.",
    fields: [
      "Receipt number and date",
      "Payer (building owner or representative) name",
      "Recipient name and role (contractor, worker, supplier)",
      "Amount paid in GHS",
      "Payment method (cash, MTN MoMo, Vodafone Cash, bank transfer, cheque)",
      "Purpose of payment (phase, milestone, or specific work)",
      "Running total of payments to date (for this recipient)",
      "Remaining balance (if part of a larger contract)",
      "Signature of recipient",
      "Signature or acknowledgment of payer",
    ],
    required: true,
  },
  {
    id: "ghana-site-plan",
    name: "Site Plan",
    type: "PLAN",
    phase: "DESIGN",
    description:
      "Site plan showing the building footprint positioned on the plot, including setbacks from property boundaries, access routes, compound wall, septic tank location, borehole position, and utility connections. Required for the development permit application and land registration.",
    fields: [
      "Plot boundaries with dimensions",
      "Building footprint with setback dimensions",
      "Orientation (north arrow)",
      "Access from the road (vehicular and pedestrian)",
      "Compound wall layout",
      "Gate location",
      "Septic tank position and distance from building",
      "Borehole location (if applicable)",
      "Utility connection points (ECG, GWCL)",
      "Neighboring buildings (existing)",
      "Scale and title block with surveyor's stamp",
    ],
    required: true,
  },
  {
    id: "ghana-permit-application",
    name: "Development Permit Application",
    type: "PERMIT",
    phase: "APPROVE",
    description:
      "Building (development) permit application form submitted to the MMDA Physical Planning Department. This is the official request to begin construction and must be accompanied by the required supporting documents.",
    fields: [
      "Applicant (building owner) full name and address",
      "Plot location (area, street, plot number)",
      "Type of development (residential, commercial, mixed)",
      "Number of storeys",
      "Total built area in square meters",
      "Estimated construction cost in GHS",
      "Reference to land documents (indenture or land certificate number)",
      "Architect name and registration number",
      "Structural engineer name and registration number (if multi-storey)",
      "List of attached documents",
      "Date and signature of applicant",
    ],
    required: true,
  },
  {
    id: "ghana-tenancy-agreement",
    name: "Tenancy Agreement",
    type: "CONTRACT",
    phase: "OPERATE",
    description:
      "Rental agreement between landlord and tenant, compliant with the Rent Act, 1963 (Act 220) and the Rent Control regulations. Defines the rental terms, advance rent, obligations of both parties, and conditions for termination. In Ghana, advance rent of 6-24 months is common market practice.",
    fields: [
      "Landlord full name and address",
      "Tenant full name and address",
      "Property description and address",
      "Monthly rent amount in GHS",
      "Advance rent period and total amount paid",
      "Tenancy duration and renewal terms",
      "Security deposit amount (if any)",
      "Maintenance responsibilities (landlord vs tenant)",
      "Utility payment responsibilities",
      "Conditions for rent increase",
      "Notice period for termination",
      "Dispute resolution mechanism",
      "Signatures of landlord, tenant, and witnesses",
    ],
    required: false,
  },
];
