import Link from "next/link";
import { KeystoneIcon } from "@/components/icons/KeystoneIcon";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 py-6 flex items-center justify-between">
          <Link href="/" className="inline-flex items-center gap-2">
            <KeystoneIcon size={24} className="text-earth" />
            <span
              className="text-[15px] font-semibold text-earth tracking-tight"
              style={{ fontFamily: "var(--font-body)" }}
            >
              KEYSTONE
            </span>
          </Link>
          <Link
            href="/privacy"
            className="text-[13px] text-muted hover:text-earth transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <h1
          className="text-[32px] text-earth mb-2"
          style={{ fontFamily: "var(--font-heading)" }}
        >
          Terms of Service
        </h1>
        <p className="text-[13px] text-muted mb-10">Last updated: March 16, 2026</p>

        <div className="space-y-8 text-[13px] text-foreground leading-relaxed">
          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              1. Service Description
            </h2>
            <p>
              Keystone is a construction project management platform that helps owner-builders plan, manage, and track residential construction projects. The platform provides tools for budget tracking, schedule management, document generation, photo documentation, contractor management, and AI-powered construction guidance. Keystone serves builders in the United States and West Africa (Togo, Ghana, and Benin).
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              2. Account Responsibilities
            </h2>
            <p className="mb-3">By creating a Keystone account, you agree to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Provide accurate and complete registration information.</li>
              <li>Maintain the security of your account credentials and not share them with others.</li>
              <li>Notify us immediately of any unauthorized access to your account.</li>
              <li>Accept responsibility for all activity that occurs under your account.</li>
            </ul>
            <p className="mt-3">
              You must be at least 18 years old to create an account and use the service.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              3. Acceptable Use
            </h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Use the service for any unlawful purpose or in violation of any applicable laws.</li>
              <li>Upload content that is fraudulent, misleading, defamatory, or infringes on the rights of others.</li>
              <li>Attempt to gain unauthorized access to other users' accounts or data.</li>
              <li>Interfere with the proper functioning of the platform or its infrastructure.</li>
              <li>Use automated tools to scrape, crawl, or extract data from the service without permission.</li>
              <li>Resell or redistribute the service without written authorization.</li>
            </ul>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              4. AI Features Disclaimer
            </h2>
            <p className="mb-3">
              Keystone includes AI-powered features that provide construction guidance, budget analysis, schedule recommendations, and other advisory content. This content is generated by artificial intelligence and is intended for educational and informational purposes only.
            </p>
            <p className="mb-3">
              <strong>AI-generated content does not constitute professional advice.</strong> The guidance provided by AI features should not be treated as a substitute for advice from licensed architects, engineers, contractors, attorneys, or financial professionals.
            </p>
            <p>
              Keystone does not guarantee the accuracy, completeness, or suitability of any AI-generated content for your specific situation. You are solely responsible for verifying all AI-generated recommendations before acting on them.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              5. Construction Disclaimer
            </h2>
            <p className="mb-3">
              Keystone is a project management and educational tool. It is not a substitute for professional construction services. You should always consult licensed professionals for decisions related to:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Structural engineering and design.</li>
              <li>Electrical, plumbing, and mechanical systems.</li>
              <li>Building code compliance and permitting.</li>
              <li>Land surveys, title verification, and legal matters.</li>
              <li>Financial planning, loan qualification, and insurance.</li>
            </ul>
            <p className="mt-3">
              Keystone is not liable for any construction defects, safety incidents, regulatory violations, financial losses, or other damages resulting from decisions made using the platform.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              6. Payment Terms
            </h2>
            <p className="mb-3">
              Keystone offers multiple subscription plans, including a free Starter tier. Paid plans (Builder, Developer, Enterprise) are billed monthly or annually as selected at the time of purchase.
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>Subscription fees are charged at the beginning of each billing period.</li>
              <li>You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period.</li>
              <li>Refunds are not provided for partial billing periods.</li>
              <li>We reserve the right to change pricing with 30 days advance notice to existing subscribers.</li>
              <li>Failed payments may result in temporary suspension of premium features until payment is resolved.</li>
            </ul>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              7. Intellectual Property
            </h2>
            <p className="mb-3">
              You retain ownership of all content you upload to Keystone, including project data, photos, and documents. By using the service, you grant Keystone a limited license to store, process, and display your content solely for the purpose of providing the service to you.
            </p>
            <p>
              The Keystone platform, including its design, code, branding, and documentation, is the intellectual property of Keystone and is protected by applicable copyright and trademark laws.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              8. Limitation of Liability
            </h2>
            <p className="mb-3">
              To the maximum extent permitted by law, Keystone and its officers, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service. This includes, but is not limited to, loss of profits, data, or business opportunities.
            </p>
            <p>
              Our total liability for any claim related to the service shall not exceed the amount you have paid to Keystone in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              9. Termination
            </h2>
            <p className="mb-3">
              You may terminate your account at any time by deleting it from the Settings page. Upon termination, your data will be permanently deleted in accordance with our Privacy Policy.
            </p>
            <p>
              We reserve the right to suspend or terminate your account if you violate these terms, engage in fraudulent activity, or use the service in a manner that harms other users or the platform. We will provide notice before termination when reasonably possible.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              10. Governing Law
            </h2>
            <p>
              These terms shall be governed by and construed in accordance with the laws of the State of Texas, United States, without regard to its conflict of law provisions. Any disputes arising from these terms or your use of the service shall be resolved in the courts located in Harris County, Texas.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              11. Changes to These Terms
            </h2>
            <p>
              We may update these terms from time to time. If we make material changes, we will notify you through the platform or by email at least 14 days before the changes take effect. Your continued use of Keystone after changes are posted constitutes your acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2
              className="text-[20px] text-earth mb-3"
              style={{ fontFamily: "var(--font-heading)" }}
            >
              12. Contact Us
            </h2>
            <p>
              If you have questions about these terms, contact us at{" "}
              <a
                href="mailto:legal@keystone.build"
                className="text-clay underline hover:text-earth transition-colors"
              >
                legal@keystone.build
              </a>.
            </p>
          </section>
        </div>

        {/* Footer nav */}
        <div className="mt-12 pt-8 border-t border-border flex items-center justify-between">
          <Link
            href="/"
            className="text-[13px] text-muted hover:text-earth transition-colors"
          >
            Back to home
          </Link>
          <Link
            href="/privacy"
            className="text-[13px] text-muted hover:text-earth transition-colors"
          >
            Privacy Policy
          </Link>
        </div>
      </main>
    </div>
  );
}
